# SPDX-FileCopyrightText: 2024 The TetriQ authors
#
# SPDX-License-Identifier: CC0-1.0

[book]
authors = ["Noé Lopez", "Elwann Guillemot", "Sébastien Lucas"]
language = "en"
multilingual = false
src = "src"
title = "The TetriQ manual"
